### ISSUE TITLE
not succeeding with convertVCFtoEigenstrat.sh

### ISSUE THREAD

**Issue by gubrins** [joanam/scripts#4]
Heys Joana,

Sorry to bother you. I'm trying to use your script to convert my vcf file to eigenstrat. However, as I'm using scaffolds, I get this message for all of them: 

`Unrecognized values used for CHROM: scaffold122 - Replacing with 0.`

And at the end, my snp file is empty. I tried this script too (https://github.com/speciationgenomics/scripts/blob/master/convertVCFtoEigenstrat.sh) but I got the same problem.

Regards,
Gabriel

**Comment by joanam** [comment]
Hi Gabriel,

Try setting the scaffold names to 1. If that does not work, you can send me the first thousand lines of your vcf file and I can check what the problem is.

Best,
Joana

**Comment by gubrins** [comment]
Hi Joana,

it improved it, but I got this new error:

`Writing PLINK PED and MAP files ... 
Done.
After filtering, kept 43654680 out of a possible 54562681 Sites
Run Time = 476.00 seconds
scripts/convertVCFtoEigenstrat.sh: line 55: 10826 Killed                  awk 'BEGIN{ind=1}{printf ind"\t"$2"\t0\t0\t0\t1\t"; 
 for(i=7;i<=NF;++i) printf $i"\t";ind++;printf "\n"}' ${file}.ped > tmp.ped
scripts/convertVCFtoEigenstrat.sh: line 71: convertf: command not found
awk: cmd. line:1: fatal: cannot open file `eight_species_chrm1.snp' for reading (No such file or directory)`

**Comment by joanam** [comment]
I am not sure what got killed here. I would recommend that you try to run the script line by line copying out the code and check which of the steps fails. Let me know what the problem was. Maybe I can improve the script accordingly.

Best,
Joana

**Comment by gubrins** [comment]
Heys again Joana,

This is the error I get when I run `/prueba/eigensoft/src/convertf -p par.PED.EIGENSTRAT.asd`

` parameter file: par.PED.EIGENSTRAT.asd
genotypename: asd.ped
snpname: asd.map
indivname: asd.ped
outputformat: EIGENSTRAT
genotypeoutname: asd.eigenstratgeno
snpoutname: asd.snp
indivoutname: asd.ind
familynames: NO
*** warning.  genetic distances are in cM not Morgans
1	1:882339	100.001	882339
Killed
`

**Comment by joanam** [comment]
I have now changed the script to allow renaming of the scaffolds. You can now use it this way:
./convertVCFtoEigenstrat.sh file.vcf.gz --renameScaff

It will rename the scaffolds to "1" and make the positions cumulative, basically concatenating your scaffolds. It now also assumes a recombination rate of 2 cM/Mb. You can change this at the top of the script. The recombination rate is used to convert the bp positions to cM for the block jackknife procedure. If you do not know the recombination rate of your species, it is not a problem. Just make sure that you have more than a hundred blocks and hundreds of SNPs per block. If you get too few blocks or too many, you can modify the block size in ADMIXTOOLS. By default, the block size is set to 0.05 (the positions are in Morgan units, so this corresponds to 5 cM). 

If you still get the same error, you may have to make sure that it is not a memory issue. "Killed" could be due to surpassing a memory threshold you are allowed to use if you are e.g. running it on a cluster.

I hope this works.

Best,
Joana

**Comment by gubrins** [comment]
It worked! I think it was both, not finding the convertf function plus not enough memory. 
Thanks Joana!

**Comment by bayudewantoro** [comment]
I use ./convertVCFtoEigenstrat.sh file.vcf.gz --renameScaff but the result is ./convertVCFtoEigenstrat.sh: line 129: convertf: command not found. So what should I do? Can you give the suggestion?

**Comment by joanam** [comment]
You will need to have convertf available. Either install EIGENSOFT (https://github.com/DReichLab/EIG/tree/master) or ADMIXTOOLS (https://github.com/DReichLab/AdmixTools) or load them as modules if you work on a cluster allowing that.
